version: "3.9"

services:
  backend:
    build: ./backend
    container_name: abaqus-backend
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # export locally before compose up
    volumes:
      - ./backend/history.json:/app/history.json
      - ./backend/exported_scripts:/app/exported_scripts

  frontend:
    build: ./frontend
    container_name: abaqus-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
